### ISSUE TITLE
Things that might work.

### ISSUE THREAD

**Issue by RegisteredDogSkinner** [xShadowBlade/school-cheats#2]
The most I know about coding is just how to use bookmarklets, maybe you could figure out if these work:
https://github.com/red-stone-network/clockwork
https://github.com/3kh0/ext-remover

Also I haven't figured out how to find the extension id's of things that aren't on the web store, but this might work for removing stuff like Lightspeed Filter Agent, Gopher Buddy, GoGuardian and the like:

javascript:eval(function(p,a,c,k,e,d){e=function(c){return c.toString(36)};if(!''.replace(/^/,String)){while(c--){d[c.toString(a)]=k[c]||c.toString(a)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('d(\'c b a: (9 8 7)\').6(\',\').5(0=>{4.3.2(0,!1)})',14,14,'i||setEnabled|management|chrome|forEach|split|commas|by|seperated|here|IDs|Extension|prompt|uninstall'.split('|'),0,{}))

**Comment by xShadowBlade** [comment]
Clockwork doesn't work (atm, to the best of my knowledge), and I am working on making a tutorial for the relevant extension removers

**Comment by RegisteredDogSkinner** [comment]
Nice thanks
